title: Sample Network Architecture

resources:
  - name: InternetGateway
    type: internet_gateway

  - name: LoadBalancer
    type: elb

  - name: WebServer1
    type: ec2

  - name: WebServer2
    type: ec2

  - name: Database
    type: rds

connections:
  - from: InternetGateway
    to: LoadBalancer

  - from: LoadBalancer
    to: WebServer1

  - from: LoadBalancer
    to: WebServer2

  - from: WebServer1
    to: Database

  - from: WebServer2
    to: Database
