nodes:
  - id: aws
    label: AWS Cloud
    shape: cloud
  - id: azure
    label: Azure Cloud
    shape: cloud
  - id: gcp
    label: GCP Cloud
    shape: cloud

  - id: aws-vpc
    label: AWS VPC (10.10.0.0/16)
    parent: aws
  - id: azure-vnet
    label: Azure VNet (10.20.0.0/16)
    parent: azure
  - id: gcp-vpc
    label: GCP VPC (10.30.0.0/16)
    parent: gcp

edges:
  - from: aws-vpc
    to: azure-vnet
    label: IPSec VPN
  - from: aws-vpc
    to: gcp-vpc
    label: IPSec VPN
  - from: azure-vnet
    to: gcp-vpc
    label: IPSec VPN
