title: Sample Network Architecture
resources:
  - name: Web Server
    type: ec2
  - name: Load Balancer
    type: elb
  - name: Internet Gateway
    type: internet_gateway
  - name: Database
    type: rds

connections:
  - from: Internet Gateway
    to: Load Balancer
  - from: Load Balancer
    to: Web Server
  - from: Web Server
    to: Database
