multi_cloud_network:
  aws:
    region: ap-southeast-1
    vpc: 10.10.0.0/16
    subnets:
      - 10.10.1.0/24
      - 10.10.2.0/24
  azure:
    region: southeastasia
    vnet: 10.20.0.0/16
    subnets:
      - 10.20.1.0/24
      - 10.20.10.0/24
  gcp:
    region: asia-southeast1
    vpc: 10.30.0.0/16
    subnets:
      - 10.30.1.0/24
      - 10.30.10.0/24

connectivity:
  - aws <-> azure: ipsec-vpn
  - aws <-> gcp: ipsec-vpn
  - azure <-> gcp: ipsec-vpn

security_controls:
  - centralized_firewalls
  - zero_trust_network_access
  - logging_and_monitoring

dns:
  - aws-route53
  - azure-private-dns
  - gcp-cloud-dns
