title: Sample Network
resources:
  - name: WebServer1
    type: ec2
  - name: LoadBalancer1
    type: elb
  - name: DB1
    type: rds
connections:
  - from: LoadBalancer1
    to: WebServer1
  - from: WebServer1
    to: DB1
