name: Generate Network Diagrams

on:
  push:
    branches: [main]
    paths:
      - 'configs/**'
      - 'src/**'
      - '.github/workflows/diagram.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install -r requirements.txt

      - name: Run generate_all.py
        run: |
          PYTHONPATH=src python src/generate_all.py

      - name: Generate multi-tier cloud app diagram
        run: python diagrams/multi_tier_cloud_app.py

      - name: Commit and push diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -f outputs/*.png
          git commit -m "🔄 Auto-generate diagrams [skip ci]" || echo "No changes to commit"
          git push
