name: Generate Network Diagrams

on:
  push:
    branches: [main]
    paths:
      - 'configs/**'
      - 'src/**'
      - '.github/workflows/diagram.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install -r requirements.txt

      - name: Generate diagrams from config files
        run: |
          mkdir -p outputs
          found_files=0
          for file in configs/*.yaml configs/*.yml configs/*.json; do
            if [ -e "$file" ]; then
              found_files=1
              base=$(basename "$file" | cut -d. -f1)
              python -c "import yaml, json, os, sys; \
from src.diagram_generator import generate_diagram_from_yaml; \
ext = os.path.splitext('$file')[1].lower(); \
with open('$file') as f: \
  data = yaml.safe_load(f) if ext in ['.yaml', '.yml'] else json.load(f); \
generate_diagram_from_yaml(data, filename=f'outputs/{base}')"
            fi
          done
          if [ $found_files -eq 0 ]; then
            echo "No config files found, skipping diagram generation."
          fi

      - name: Generate multi-tier cloud app diagram
        run: |
          python diagrams/multi_tier_cloud_app.py

      - name: Commit and push diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -f outputs/*.png
          git commit -m "🔄 Auto-generate diagrams [skip ci]" || echo "No changes to commit"
          git push
