name: Generate Network Diagram

on:
  push:
    paths:
      - 'configs/**'
      - 'src/**'
      - '.github/workflows/diagram.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
     permissions:
      contents: write  # ✅ Allow push to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Graphviz and Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install -r requirements.txt

      - name: Generate network diagrams
        run: |
          mkdir -p outputs
          for cfg in configs/*.{yml,yaml,json}; do
            [ -e "$cfg" ] || continue
            fname=$(basename "$cfg" | sed 's/\.[^.]*$//')
            python src/main.py --config "$cfg" --output "outputs/${fname}.png"
          done

      - name: Commit and push generated diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -f outputs/*.png
          git commit -m "🔄 Auto-generate diagrams [skip ci]" || echo "No changes to commit"
          git push
