name: Generate Network Diagrams

on:
  push:
    branches: [main]
    paths:
      - 'configs/**'
      - 'src/**'
      - '.github/workflows/diagram.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install -r requirements.txt

      - name: Generate diagrams
        run: |
          mkdir -p outputs
          for cfg in configs/*.{yml,yaml,json}; do
            [ -e "$cfg" ] || continue
            fname=$(basename "$cfg" | sed 's/\.[^.]*$//')
            python src/cli.py --config "$cfg" --output "outputs/${fname}.png"
          done

      - name: Commit and push diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -f outputs/*.png
          git commit -m "🔄 Auto-generate diagrams [skip ci]" || echo "No changes to commit"
          git push
