name: Generate On-Prem Network Diagram

on:
  push:
    paths:
      - diagrams/onprem_network_architecture.py
      - .github/workflows/generate-diagram.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (Graphviz)
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install Python dependencies
      run: pip install diagrams

    - name: Generate Diagram
      run: python diagrams/onprem_network_architecture.py

    - name: Upload Diagram Artifact
      uses: actions/upload-artifact@v4
      with:
        name: onprem-diagram
        path: on-prem-network-architecture.png
